### PR TITLE
chore: upgrade dependencies in preparation for svelte 5

### PR DESCRIPTION
**Pull request by benmccann**
Minimum versions of a number of different Svelte packages must be used in order to support Svelte 5

### CODE REVIEW

**Comment by RobBrazier** [comment]
apologies for the delay on getting to this, thanks for the PR! I'll be honest I haven't kept up with svelte lately

the sveltekit dependencies are mainly for the demo site really - there aren't any production dependencies as I was just using stuff from vanilla svelte (and that was a peer dependency anyway)

Good to update nonetheless, I haven't tested with svelte 5 yet to see whether it actually doesn't work though

**Comment by benmccann** [comment]
Svelte 5 can work with components written in Svelte 4 syntax and I've been using this library in that fashion for a long time. I'd like to send a PR to upgrade this library to Svelte 5 runes syntax once the final release of Svelte 5 is out. This is something that would be required for that. I thought I'd send this piece of it now to break things up and make that PR a bit smaller. This PR should work just fine with Svelte 4 in the meantime

**Review by RobBrazier — APPROVED** [review]

**Comment by RobBrazier** [comment]
I was testing with svelte 5 and currently I can't install due to the peerDependencies not including v5 (it does work though when using local folders)
unsure if there's something 'special' with pre-release/next versions, but with version [3.3.3](https://github.com/RobBrazier/svelte-awesome/releases/tag/v3.3.3) even having a lower and upper bounds `>= 3.43.1 < 6` it can't install currently

it works fine with that peerDependencies value on svelte 4, but I've had issues with peerDependencies before so am just going to leave it as-is for now 😓

**Comment by benmccann** [comment]
You can normally ignore the peer dependency warnings, which is what I've been doing

**Pull request merged**
